// ! NEVER EVER USE THIS FILE DIRECTLY 
// ! ALWAYS ADD NEW ENTRIES AT THE END
// ! DO NOT MODIFY OR REMOVE EXISTING ENTRIES
// ! BE SURE DEFAULT VALUES DO NOT EXCEEDS TYPE SIZE

//  name| type| def
DATA(data1, int, 15)